
language: c

script: 
    - sudo add-apt-repository ppa:sonkun/sfml -y
    - sudo rm -rf /var/lib/apt/lists/*
    - sudo apt-get clean
    - sudo apt-get update
    - sudo apt-get install libcsfml -y
    - make all

compiler: 
    - gcc
